#!/usr/bin/env python3
"""Download, optimize, inventory, and wire the approved Community Cuts photo set.

Source: Google Drive folder supplied by the ASC3ND owner.
Destination: public/images/projects/community-cuts/*.jpg

This pipeline intentionally stores web-ready derivatives in GitHub rather than multi-megabyte
camera originals. The originals remain in the owner-controlled Drive folder.
"""

from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

import gdown
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SOURCE_FOLDER = "https://drive.google.com/drive/folders/1QXJK7WwEqhugArmSiFVh_Ysq7Ci1dDB8"
RAW_DIR = ROOT / ".tmp" / "community-cuts-drive"
DEST_DIR = ROOT / "public" / "images" / "projects" / "community-cuts"
MANIFEST_TS = ROOT / "lib" / "community-cuts-media.generated.ts"
PROJECTS_TS = ROOT / "lib" / "projects.ts"
AUDIT_JSON = ROOT / "docs" / "community-cuts" / "PHOTO_IMPORT_AUDIT.json"
EXPECTED_COUNT = 86
MAX_LONG_EDGE = 1600
JPEG_QUALITY = 82


def natural_key(path: Path):
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", path.name)]


def download_source() -> list[Path]:
    if RAW_DIR.exists():
        shutil.rmtree(RAW_DIR)
    RAW_DIR.mkdir(parents=True, exist_ok=True)

    result = gdown.download_folder(
        url=SOURCE_FOLDER,
        output=str(RAW_DIR),
        quiet=False,
        use_cookies=False,
    )
    if not result:
        raise RuntimeError("Google Drive folder download returned no files")

    photos = sorted(
        [
            path
            for path in RAW_DIR.rglob("*")
            if path.is_file() and path.suffix.lower() in {".jpg", ".jpeg"}
        ],
        key=natural_key,
    )
    if len(photos) != EXPECTED_COUNT:
        raise RuntimeError(f"Expected {EXPECTED_COUNT} photos, downloaded {len(photos)}")
    return photos


def optimize(photos: list[Path]) -> list[dict]:
    if DEST_DIR.exists():
        shutil.rmtree(DEST_DIR)
    DEST_DIR.mkdir(parents=True, exist_ok=True)

    manifest: list[dict] = []
    for index, source in enumerate(photos, start=1):
        output_name = f"community-cuts-{index:03d}.jpg"
        destination = DEST_DIR / output_name

        with Image.open(source) as original:
            image = ImageOps.exif_transpose(original).convert("RGB")
            width, height = image.size
            longest = max(width, height)
            if longest > MAX_LONG_EDGE:
                scale = MAX_LONG_EDGE / longest
                image = image.resize(
                    (max(1, round(width * scale)), max(1, round(height * scale))),
                    Image.Resampling.LANCZOS,
                )
            out_width, out_height = image.size
            image.save(
                destination,
                format="JPEG",
                quality=JPEG_QUALITY,
                optimize=True,
                progressive=True,
            )

        manifest.append(
            {
                "id": f"community-cuts-photo-{index:03d}",
                "type": "image",
                "src": f"/images/projects/community-cuts/{output_name}",
                "alt": f"Community Cuts for Kids event photo {index}",
                "caption": "Community Cuts for Kids · Everett, Washington · August 2026",
                "approved": True,
                "consentConfirmed": True,
                "featured": index == 1,
                "width": out_width,
                "height": out_height,
                "sourceFile": source.name,
                "bytes": destination.stat().st_size,
            }
        )
    return manifest


def write_typescript(manifest: list[dict]) -> None:
    lines = [
        'import type { ProjectMediaItem } from "./projects";',
        "",
        "// Generated by scripts/import-community-cuts-photos.py.",
        "// Owner authorized publication of the supplied Community Cuts photo set on 2026-09-16.",
        "export const communityCutsMedia: ProjectMediaItem[] = [",
    ]
    for item in manifest:
        lines.extend(
            [
                "  {",
                f'    id: "{item["id"]}",',
                '    type: "image",',
                f'    src: "{item["src"]}",',
                f'    alt: "{item["alt"]}",',
                f'    caption: "{item["caption"]}",',
                "    approved: true,",
                "    consentConfirmed: true,",
                f'    featured: {str(item["featured"]).lower()},',
                f'    width: {item["width"]},',
                f'    height: {item["height"]},',
                "  },",
            ]
        )
    lines.extend(["];", ""])
    MANIFEST_TS.write_text("\n".join(lines), encoding="utf-8")


def wire_project_model() -> None:
    source = PROJECTS_TS.read_text(encoding="utf-8")
    import_line = 'import { communityCutsMedia } from "./community-cuts-media.generated";\n\n'
    if import_line.strip() not in source:
        source = import_line + source

    source, count = re.subn(
        r'(export const communityCutsProject: Asc3ndProject = \{[\s\S]*?featuredFilm: \{[\s\S]*?\},\n)  media: \[\],',
        r'\1  media: communityCutsMedia,',
        source,
        count=1,
    )
    if count != 1 and "media: communityCutsMedia," not in source:
        raise RuntimeError("Could not wire generated Community Cuts media into lib/projects.ts")

    PROJECTS_TS.write_text(source, encoding="utf-8")


def write_audit(manifest: list[dict]) -> None:
    AUDIT_JSON.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "sourceFolder": SOURCE_FOLDER,
        "expectedCount": EXPECTED_COUNT,
        "importedCount": len(manifest),
        "maxLongEdge": MAX_LONG_EDGE,
        "jpegQuality": JPEG_QUALITY,
        "outputDirectory": str(DEST_DIR.relative_to(ROOT)),
        "totalOptimizedBytes": sum(item["bytes"] for item in manifest),
        "items": [
            {
                "sourceFile": item["sourceFile"],
                "src": item["src"],
                "width": item["width"],
                "height": item["height"],
                "bytes": item["bytes"],
            }
            for item in manifest
        ],
    }
    AUDIT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    photos = download_source()
    manifest = optimize(photos)
    write_typescript(manifest)
    wire_project_model()
    write_audit(manifest)
    print(f"Imported {len(manifest)} Community Cuts photos")
    print(f"Optimized bytes: {sum(item['bytes'] for item in manifest):,}")


if __name__ == "__main__":
    main()
